// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF0FbdQhzt3QTJkPwtdtUdCU1aDmo78l8',
    appId: '1:525335951605:web:9866ad7afe1918d815edbc',
    messagingSenderId: '525335951605',
    projectId: 'rental-app-30a59',
    authDomain: 'rental-app-30a59.firebaseapp.com',
    storageBucket: 'rental-app-30a59.firebasestorage.app',
    measurementId: 'G-E1D2LYK1PZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrKjWhvZxaPGqYn2KnhkbIh0O0zGJVG70',
    appId: '1:525335951605:android:2cccc35968e63d1c15edbc',
    messagingSenderId: '525335951605',
    projectId: 'rental-app-30a59',
    storageBucket: 'rental-app-30a59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC78EljUFNfth7jzFCz_dGQouP3yMekSQc',
    appId: '1:525335951605:ios:8b8910234b78840015edbc',
    messagingSenderId: '525335951605',
    projectId: 'rental-app-30a59',
    storageBucket: 'rental-app-30a59.firebasestorage.app',
    iosBundleId: 'com.example.rentalApp',
  );
}
